export const imageTypes = Object.freeze({
	SET_CURRENT_DATA: 'SET_CURRENT_DATA',
	SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
	SET_MESSAGE: 'SET_MESSAGE',
	SET_IMAGE_STATUS: 'SET_IMAGE_STATUS',
	LOAD_HISTORY: 'LOAD_HISTORY',
});
